### ISSUE TITLE
Missing dependencies in useEffect in react-example-initTokenize

### ISSUE THREAD

**Issue by Mhmdabed11** [datatrans/secure-fields-sample#27]
## Problem Description
I am trying to use the react-example-initTokenize sample provided. I noticed that there are missing dependencies in the array in useEffect in the code.

## Example 1
In the code below, the useEffect is missing 4 dependencies which are: 
Here is a link to the code: https://github.com/datatrans/secure-fields-sample/blob/master/react-example-initTokenize/src/SecureFields.js#L51
`cleanupSecureFields, initSecureFields, production, secureFields` .

![image](https://user-images.githubusercontent.com/39762577/199698026-8a843c48-7b92-41f9-bf82-5d2468ec89da.png)

## Example 2
In the code below, the useEffect is missing some dependancies: `cardContainerClassNames, cvvContainerClassNames, secureFields`
Here is a link to the code: https://github.com/datatrans/secure-fields-sample/blob/master/react-example-initTokenize/src/SecureFields.js#L73
![image](https://user-images.githubusercontent.com/39762577/199698908-27e77b3c-0a0d-462b-bd01-6ae32da146e9.png)

## Proposed Solution:
I believe that the dependencies should be added to avoid rendering bugs.

**Comment by pstadler** [comment]
So, does it work for you, or are you seeing any bugs?

- The dependency array in _Example 1_ is empty on purpose - we only want to run this once
- The dependency array in _Example 2_ contains `secureFields`, because we want to register callbacks **once**, as soon as `secureFields` has been made available

Please let us know if something does indeed lead to rendering being buggy.
